openapi: '3.0.0'
info:
  title: bc-api
  version: '1.0'
  license:
    name: 'https://api-b2b.bigcommerce.com/api/v2'
  description: ''
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /bcauth:
    get:
      summary: Get bigcommerce auth
      tags:
        - bc-api
      responses: {}
      operationId: get-bcauth
      description: Get bigcommerce auth
      parameters:
        - schema:
            type: string
          in: query
          name: context
        - schema:
            type: string
          in: query
          name: code
        - schema:
            type: string
          in: query
          name: scope
      x-internal: true
  /bcload:
    get:
      summary: Get bigcommerce load
      tags:
        - bc-api
      responses: {}
      operationId: get-bcload
      parameters:
        - schema:
            type: string
          in: query
          name: signed_payload
      description: Get bigcommerce load
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: bc-api
x-internal: true
