openapi: '3.0.0'
info:
  title: catalog
  version: '1.0'
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /catalogs:
    get:
      summary: Get Catalog List
      tags:
        - catalog
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties:
                      list:
                        type: array
                        uniqueItems: true
                        minItems: 1
                        items:
                          required:
                            - catalogId
                            - catalogName
                          properties:
                            catalogId:
                              type: string
                              minLength: 1
                            catalogName:
                              type: string
                              minLength: 1
                      pagination:
                        type: object
                        properties:
                          totalCount:
                            type: number
                          offset:
                            type: number
                          limit:
                            type: number
                        required:
                          - totalCount
                          - offset
                          - limit
                    required:
                      - list
                      - pagination
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      list:
                        - catalogId: '1'
                          catalogName: Wholesale001
                        - catalogId: '2'
                          catalogName: allenB2b
                        - catalogId: '5'
                          catalogName: test
                        - catalogId: '6'
                          catalogName: s-test1 pricelist
                        - catalogId: '7'
                          catalogName: Wholesale0011
                        - catalogId: '8'
                          catalogName: allenB2b1
                        - catalogId: '9'
                          catalogName: test1
                        - catalogId: '10'
                          catalogName: s-test1 pricelist1
                        - catalogId: '11'
                          catalogName: Wholesale group
                        - catalogId: '13'
                          catalogName: price test 1
                      pagination:
                        totalCount: 13
                        offset: 0
                        limit: 10
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      list:
                        - catalogId: '1'
                          catalogName: Wholesale001
                        - catalogId: '2'
                          catalogName: allenB2b
                      pagination:
                        totalCount: 2
                        offset: 0
                        limit: 10
      operationId: get-catalogs
      description: Get Catalog List
      parameters:
        - schema:
            type: string
          in: query
          name: q
          description: Query string
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: catalog
x-internal: true
