openapi: '3.0.0'
info:
  title: other
  version: '1.0'
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /health-check:
    get:
      summary: Check django service health
      tags:
        - other
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties: {}
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data: {}
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data: {}
      operationId: get-health-check
      description: Check django service health
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: other
x-internal: true
