openapi: '3.0.0'
info:
  title: proxy
  version: '1.0'
  description: ''
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /proxy/b2c:
    post:
      summary: BigCommerce S2S API proxy with auth
      operationId: post-proxy-b2c
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties: {}
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data: {}
              examples:
                example-1:
                  value:
                    code: 0
                    message: string
                    data: {}
      description: BigCommerce S2S API proxy with auth
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                function_name:
                  type: string
                bc_token:
                  type: string
                customer:
                  type: object
                  required:
                    - id
                  properties:
                    id:
                      type: string
                store_hash:
                  type: string
              required:
                - function_name
                - bc_token
                - store_hash
      tags:
        - proxy
      x-internal: true
  /proxy:
    post:
      summary: Third party API proxy
      operationId: post-proxy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties: {}
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data: {}
      description: Third party API proxy
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                method:
                  type: string
                  default: get
                url:
                  type: string
                params:
                  type: object
                data:
                  type: object
                proxyType:
                  type: string
                  default: Bigcommerce
      tags:
        - proxy
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: proxy
x-internal: true
