openapi: '3.0.0'
info:
  title: quantity_limit
  version: '1.0'
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /qty/upload:
    get:
      summary: Get Upload Quantity Limit Data
      tags:
        - quantity-limit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      socketId: e5e6a732b9d824565b4241f7ddd187d9
                      isReady: '1'
                      fileUrl: 'https://s3-us-west-2.amazonaws.com/bundleb2b-v2.0-qty-staging/product_quantity_limit_export_1i6zpxpe3g.xls'
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - socketId
                      - isReady
                      - fileUrl
                    properties:
                      socketId:
                        type: string
                        minLength: 1
                      isReady:
                        type: string
                        minLength: 1
                        description: '"0":doing, "1":finished'
                      fileUrl:
                        type: string
                        minLength: 1
                        description: File download address
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      socketId: e5e6a732b9d824565b4241f7ddd187d9
                      isReady: '1'
                      fileUrl: url
      operationId: get-qty-upload
      description: Get Upload Quantity Limit Data
      x-internal: true
    post:
      summary: Upload Quantity Limit File
      operationId: post-qty-upload
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      isReady: '0'
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - isReady
                    properties:
                      isReady:
                        type: string
                        minLength: 1
                        description: '"0":doing, "1":finished'
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      isReady: '0'
      description: Upload Quantity Limit File
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: object
            examples: {}
        description: ''
      tags:
        - quantity-limit
      x-internal: true
  /qty/export:
    get:
      summary: Get Export Quantity Limit Data
      tags:
        - quantity-limit
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties:
                      fileUrl:
                        type: string
                        minLength: 1
                    required:
                      - fileUrl
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      fileUrl: 'https://s3-us-west-2.amazonaws.com/bundleb2b-v2.0-qty-staging/product_quantity_limit_export_1i6zpxpe3g.xls'
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      fileUrl: url
      operationId: get-qty-export
      description: Get Export Quantity Limit Data
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: quantity-limit
x-internal: true
