openapi: '3.0.0'
info:
  title: store
  version: '1.0'
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /stores/themes:
    post:
      summary: Upload store theme.
      operationId: post-stores-themes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    properties: {}
                required:
                  - code
                  - message
                  - data
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data: {}
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data: {}
      description: Upload store theme.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                storeHash:
                  type: string
                baseStoreHash:
                  type: string
                themeName:
                  type: string
              required:
                - storeHash
                - baseStoreHash
                - themeName
      tags:
        - store
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: store
x-internal: true
