openapi: '3.0.0'
info:
  title: subscription
  version: '1.0'
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /subscription:
    post:
      summary: Create a subscription
      operationId: post-subscription
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: object
                properties: {}
              examples: {}
      description: Create a subscription
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                record_id:
                  type: string
                company:
                  type: string
                email:
                  type: string
                cardholder_name:
                  type: string
                credit_card_number:
                  type: string
                expiration_date:
                  type: string
                cvv:
                  type: string
                first_name:
                  type: string
                last_name:
                  type: string
                street_address:
                  type: string
                city:
                  type: string
                state:
                  type: string
                postal_code:
                  type: string
                country:
                  type: string
        description: ''
      tags:
        - subscription
      x-internal: true
  '/subscriptions/{record_id}':
    parameters:
      - schema:
          type: string
        name: record_id
        in: path
        required: true
    get:
      summary: Get subscription by id
      tags:
        - subscription
      responses:
        '200':
          description: OK
          content:
            text/html:
              schema:
                type: object
                properties: {}
      operationId: get-subscriptions-record_id
      description: Get subscription by id
      x-internal: true
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: subscription
x-internal: true
