blank_issues_enabled: false
contact_links:
  - name: Get BigCommerce help
    url: https://support.bigcommerce.com/s/contact
    about:
      If you need to file a BigCommerce bug report or platform outage, contact our Support team. Contact information is in the store control panel. Partners, please use your Partner Portal to open a case. 
  - name: Docs + DevCenter feature request
    url: https://github.com/bigcommerce/docs/discussions/new?category=ideas-feature-requests
    about:
      We appreciate you taking the time to improve our docs! Meet us in Discussions to talk further about your feature request.
  - name: 💬 BigCommerce community
    url: https://developer.bigcommerce.com/community
    about: Meet and chat with other people building with BigCommerce.
