name: 🖍️ Incorrect documentation report
description: Something is wrong or missing from the docs.
labels:
  - 'bug:unverified'
body:
  - type: markdown
    attributes:
      value: |
        Thank you for helping improve the BigCommerce DevDocs!

        ## Tell us what's missing!

  - type: input
    attributes:
      label: What is the link to the page that needs updating? Provide multiple links if needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What needs to be documented?
      description: A concise description of what you expect to see here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: What is currently documented?
      description: A concise description of what you're actually seeing.
    validations:
      required: true
