blank_issues_enabled: false
contact_links:
  - name: Have questions?
    url: https://developer.bigcommerce.com/docs/build
    about:
      Explore the dev docs.
  - name: Feature request
    url: https://github.com/bigcommerce/docs/discussions/new?category=ideas-feature-requests
    about:
      Join us in Discussions to share your idea on improving our docs. Thanks for your contribution!
  - name: Need help with our docs?
    url: https://support.bigcommerce.com/s/contact
    about:
      To report an outage or greater platform issue, contact our Technical Support team. If you're a partner, please do so via your Partner Portal.
  - name: 💙 Join the BigCommerceDevs community
    url: https://developer.bigcommerce.com/community
    about: Connect with other devs building on BigCommerce!

