openapi: '3.0.1'
info:
  title: Storefront Form Fields (Beta)
  description: |-
    Read form fields on BigCommerce-hosted storefronts. To work with headless storefronts, use the [GraphQL Storefront API](/graphql-storefront/reference).
    
    The REST Storefront API uses [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) headers for authentication, and therefore has no required scopes. You do not need to send any BigCommerce-specific tokens with your requests to these endpoints.
        
    For info about authenticating BigCommerce APIs, see [Authentication and Example Requests](/docs/start/authentication#same-origin-cors-authentication).

    > #### Warning
    > Breaking changes may be introduced to this endpoint while in beta.
  version: ''
  termsOfService: 'https://www.bigcommerce.com/terms'
  contact:
    name: BigCommerce
    url: 'https://www.bigcommerce.com'
    email: support@bigcommerce.com
servers:
  - url: 'https://{store_domain}/api/storefront'
    variables:
      store_domain:
        default: your_store.example.com
        description: 'The [URL authority](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL#authority) of the storefront.'
tags:
  - name: Form Fields
paths:
  /form-fields:
    get:
      tags:
        - Form Fields
      summary: Get Form Fields
      operationId: getFormFields
      description: |-
        Gets form fields.

        > #### Note
        > * Substitute your storefront domain for `yourstore.example.com`. 
        > * The Send a Test Request feature is not currently supported for this endpoint.
      parameters:
        - name: filter
          in: query
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
              enum:
                - customerAccount
                - shippingAddress
                - billingAddress
      responses:
        '200':
          description: Returns an object with form fields groups.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormFieldGroups'
components:
  schemas:
    FormFieldGroups:
      type: object
      description: Group of form field groups
      x-internal: false
      properties:
        customerAccount:
          $ref: '#/components/schemas/FormFields'
        shippingAddress:
          $ref: '#/components/schemas/FormFields'
        billingAddress:
          $ref: '#/components/schemas/FormFields'
    FormFields:
      type: array
      description: List of form fields for the group
      items:
        $ref: '#/components/schemas/FormField'
      x-internal: false
    FormField:
      type: object
      properties:
        id:
          type: string
          description: Field unique ID
        name:
          type: string
          description: Field name
        custom:
          type: boolean
          description: Whether this is a custom field or system built-in field.
        label:
          type: string
          description: User-friendly label
        required:
          type: boolean
          description: Whether this field is required or not
        default:
          type: string
          description: The field unique ID
        type:
          type: string
          description: Type of the value hold by the field
          enum:
            - integer
            - string
            - array
            - date
        fieldType:
          type: string
          description: Type of the field
          enum:
            - checkbox
            - text
            - date
            - multiline
            - radio
            - dropdown
        min:
          type: string
          description: The minimum valid value for the field (integer and date type only).
        max:
          type: string
          description: The minimum valid value for the field (integer and date type only).
        maxLength:
          type: integer
          description: The maximum length for the value (string type only).
        secret:
          type: boolean
          description: Whether the field represents a password field (password field type only).
        requirements: 
          type: object
          description: Password requirements (password field type only).  
          properties:
            alpha: 
              type: string
              description: Regex expression for the required alpha characters.
              example: '[A-Za-z]'
            description:
              type: string 
              description: Description for the password requirements. 
              example: Passwords must be at least 7 characters and contain both alphabetic and numeric characters. 
            minlength: 
              type: integer 
              description: Minimum password length. 
            numeric: 
              type: string
              description: Regex expression for the required numeric characters.
              example: '[0-9]'
        options:
          type: object
          properties:
            helperLabel:
              type: string
              description: Placeholder text for dropdown field type.
            items:
              type: array
              description: List of possible values for this field.
              items:
                type: object
                properties:
                  label:
                    type: string
                  value:
                    type: string
          description: 'Extra data for radio, dropdown and checkbox field types.'
      description: Form Field
      x-internal: false
