openapi: '3.0.0'
info:
  title: Tax Settings
  version: ''
  description: Manage tax settings
  termsOfService: 'https://www.bigcommerce.com/terms'
  contact:
    name: BigCommerce
    url: 'https://www.bigcommerce.com'
    email: support@bigcommerce.com
servers:
  - url: 'https://api.bigcommerce.com/stores/{store_hash}/v3'
    variables:
      store_hash:
        default: store_hash
        description: Permanent ID of the BigCommerce store.
    description: BigCommerce API Gateway
security:
  - X-Auth-Token: []
tags:
  - name: Tax Settings
paths:
  '/tax/settings':
    get:
      tags:
        - Tax Settings
      summary: Get Tax Settings
      description: Retrieves global-level tax settings.
      operationId: get-tax-settings
      responses:
        '200':
          description: OK
          content:
            application/json: 
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Tax_Settings'
                  meta:
                    $ref: '#/components/schemas/MetaOpen'
    put:
      tags:
        - Tax Settings
      summary: Update Tax Settings
      description: Updates global-level tax settings.
      operationId: set-tax-settings
      parameters:
      - $ref: '#/components/parameters/ContentType'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tax_Settings_Req'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Tax_Settings'
                  meta:
                    $ref: '#/components/schemas/MetaOpen'
        '422':
          description: The request body does not meet the specification.
    parameters:
      - $ref: '#/components/parameters/Accept'
components:
  parameters:
    Accept:
      name: Accept
      in: header
      required: true
      description: 'The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the response body.'
      schema:
        type: string
        default: 'application/json'
    ContentType:
      name: Content-Type
      in: header
      required: true
      description: 'The [MIME type](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types) of the request body.'
      schema:
        type: string
        default: 'application/json'
  securitySchemes:
    X-Auth-Token:
      name: X-Auth-Token
      description: |-
        ### OAuth scopes

        | UI Name | Permission | Parameter |
        |:--------|:-----------|:----------|
        |  Information & Settings | modify | `store_v2_information` |
        |  Information & Settings | read-only | `store_v2_information_read_only` |

        ### Authentication header
        
        | Header | Argument | Description |
        |:-------|:---------|:------------|
        | `X-Auth-Token` | `access_token` | For more about API accounts that generate `access_token`s, see our [Guide to API Accounts](/api-docs/getting-started/api-accounts). |
        
        ### Further reading
        
        For example requests and more information about authenticating BigCommerce APIs, see [Authentication and Example Requests](/api-docs/getting-started/authentication#x-auth-token-header-example-requests).
        
        For more about BigCommerce OAuth scopes, see our [Guide to API Accounts](/api-docs/getting-started/api-accounts#oauth-scopes).
        
        For a list of API status codes, see [API Status Codes](/api-docs/getting-started/api-status-codes).
      type: apiKey
      in: header
  schemas:
    Tax_Settings:
      type: object
      properties:
        tax_entered_with_prices:
          type: boolean
          description: Whether prices entered on this store include a tax component or not.
        price_display_settings:
          type: object
          description: Settings that describe how prices display at the global level.
          properties:
            show_inclusive_in_control_panel:
              type: boolean
              description: Whether to show prices as tax inclusive or tax exclusive in the BigCommerce control panel.
            invoice_price_display_strategy:
              type: string
              description: 'Whether to show prices as tax inclusive or tax exclusive across all invoices, or use the shopperʼs tax zone for price display on invoices.'
              default: ZONE
              enum:
                - ZONE
                - INCLUSIVE
                - EXCLUSIVE
        fallback_strategy:
          type: string
          description: 'Describes the fallback behavior that applies when a tax provider produces an error. A merchant may decide to use a flat 10% fallback tax rate, their basic tax settings, or to block the transaction until they achieve a successful result.'
          default: FIXED
          enum:
            - FIXED
            - BASIC
            - DISABLE
    Tax_Settings_Req:
      type: object
      properties:
        tax_entered_with_prices:
          type: boolean
          description: Whether prices entered on this store include a tax component or not.
        price_display_settings:
          type: object
          description: Settings that describe how prices display at the global level.
          properties:
            show_inclusive_in_control_panel:
              type: boolean
              description: Whether to show prices as tax inclusive or tax exclusive in the BigCommerce control panel.
            invoice_price_display_strategy:
              type: string
              description: 'Whether to show prices as tax inclusive or tax exclusive across all invoices, or use the shopperʼs tax zone for price display on invoices.'
              enum:
                - ZONE
                - INCLUSIVE
                - EXCLUSIVE
        fallback_strategy:
          type: string
          description: 'Decribes the fallback behaviour that applies when a tax provider produces an error. A merchant may decide to use a flat 10% fallback tax rate, their basic tax settings, or to block the transaction until a successful result can be achieved.'
          enum:
            - FIXED
            - BASIC
            - DISABLE
    MetaOpen:
      title: Response meta
      type: object
      properties: {}
      additionalProperties: true
      description: Response metadata.
