openapi: 3.0.1
info:
  title: PaymentMethod
  description: BigCommerce B2B Edition PaymentMethod
  contact: {}
  version: v3
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2/ip/storefront'
security:
  - authToken: []
tags:
  - name: PaymentMethod
    description: PaymentMethod
components:
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
paths:
  /payments/modules:
    get:
      summary: Get Payment Modules
      tags:
        - Payments
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  code:
                    type: number
                  data:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - moduleName
                      properties:
                        moduleName:
                          type: string
                          minLength: 1
                        value:
                          type: object
                          properties:
                            isEnabled:
                              type: number
                            displayName:
                              type: string
                              minLength: 1
                            isStorefrontMethod:
                              type: number
                          required:
                            - isEnabled
                            - displayName
                            - isStorefrontMethod
                  meta:
                    type: object
                    properties:
                      message:
                        type: string
                        minLength: 1
                    required:
                      - message
                required:
                  - code
                  - data
                  - meta
                x-examples:
                  example-1:
                    code: 200
                    data:
                      - moduleName: payments_offline
                        value:
                          isEnabled: 1
                          displayName: Offline Payment
                          isStorefrontMethod: 0
                      - moduleName: payments_test
                        value:
                          isEnabled: 0
                          displayName: Test Payment Gateway
                          isStorefrontMethod: 1
                      - moduleName: payments_minibc
                        value:
                          apiKey: ''
                          rootUrl: 'https://apps.minibc.com/api/apps/recurring/v1'
                          isEnabled: 1
                          displayName: Credit / Debit Card
                          authorizeOnly: 1
                          isStorefrontMethod: 1
                      - moduleName: payments_bigcommerce_sales_order
                        value:
                          isEnabled: 1
                          productId: 112
                          variantId: 77
                          displayName: Pay with BigCommerce
                          allowedMethods:
                            - bigpaypay
                            - cheque
                          isStorefrontMethod: 1
                    meta:
                      message: SUCCESS
              examples:
                example-1:
                  value:
                    code: 200
                    data:
                      - moduleName: payments_offline
                        value:
                          isEnabled: 1
                          displayName: Offline Payment
                          isStorefrontMethod: 0
                      - moduleName: payments_test
                        value:
                          isEnabled: 0
                          displayName: Test Payment Gateway
                          isStorefrontMethod: 1
                      - moduleName: payments_minibc
                        value:
                          apiKey: ''
                          rootUrl: 'https://apps.minibc.com/api/apps/recurring/v1'
                          isEnabled: 1
                          displayName: Credit / Debit Card
                          authorizeOnly: 1
                          isStorefrontMethod: 1
                      - moduleName: payments_bigcommerce_sales_order
                        value:
                          isEnabled: 1
                          productId: 112
                          variantId: 77
                          displayName: Pay with BigCommerce
                          allowedMethods:
                            - bigpaypay
                            - cheque
                          isStorefrontMethod: 1
                    meta:
                      message: SUCCESS
      operationId: get-payments-modules
      description: Get payment modules
      parameters: []
      x-internal: true
x-internal: true
