openapi: 3.0.0
info:
  title: Store Configs
  version: '1.0'
  description: Personalize information settings of stores.
servers:
  - url: 'https://api-b2b.bigcommerce.com/api/v2'
paths:
  /store-configs/switch-status:
    get:
      summary: Get Store Configs
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                x-examples:
                  example-1:
                    code: 200
                    message: SUCCESS
                    data:
                      id: '2'
                      key: interval_quantity
                      isEnabled: '0'
                properties:
                  code:
                    type: number
                  message:
                    type: string
                    minLength: 1
                  data:
                    type: object
                    required:
                      - id
                      - key
                      - isEnabled
                    properties:
                      id:
                        type: string
                        minLength: 1
                      key:
                        type: string
                        minLength: 1
                      isEnabled:
                        type: string
                        minLength: 1
                        description: Is the switch config enabled
                required:
                  - code
                  - message
                  - data
              examples:
                example-1:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      id: '1'
                      key: email_notifications
                      isEnabled: '1'
                example-2:
                  value:
                    code: 200
                    message: SUCCESS
                    data:
                      id: '2'
                      key: interval_quantity
                      isEnabled: '0'
      operationId: get-store-configs-switch-status
      parameters:
        - schema:
            type: string
            enum:
              - email_notifications
              - interval_quantity
          in: query
          name: key
          required: true
          description: 'Key of store configs. '
      description: Get the configuration list of all stores whose types are switches
      tags:
        - Store Config
      x-internal: true
components:
  schemas: {}
  securitySchemes:
    authToken:
      name: authToken
      type: apiKey
      in: header
security:
  - authToken: []
tags:
  - name: Store Config
x-internal: true
