name: Deploy Preview Build

on:
  push:
    branches:
      - trigger_circleci_deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
    - name: Trigger CircleCI Build
      run: |
        curl --location 'https://circleci.com/api/v2/project/gh/bigcommerce/developer-center/pipeline' \
        --header 'Circle-Token: ${{ secrets.CIRCLECI_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
            "branch": "main",
            # "parameters": {
            #     "build_environment": "preview",
            #     "github_triggering_actor": "${{ github.actor }}"
            # }
        }'
