name: remark
on: [pull_request]
jobs:
  remark:
    name: runner / retext-style-guide
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/retext-style-guide
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added
