name: remark
on: [pull_request]
jobs:
  remark:
    name: runner / retext-style-guide
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ./.github/actions/retext-style-guide
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added
          before_commit: ${{ github.event.before }}
          after_commit: ${{ github.sha }}