name: Lint OpenAPI
on:
  - pull_request
jobs:
  build:
    name: Run Spectral!
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli@latest

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Run and Report Spectral
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          spectral lint './reference/**/*.yml' --ruleset '.spectral.yaml' --ignore-unknown-format -f="sarif" \
          | reviewdog -level=warning -reporter=github-pr-review -filter-mode="nofilter" -f="sarif"
